---
- name: restart rsyslog
  become: yes
  service:
    name: rsyslog
    state: restarted

- name: "reload systemd"
  systemd:
    daemon_reload: yes

- name: "restart node_exporter"
  service:
    name: "node_exporter"
    state: restarted
